"""random_draws + broadcast.scheduled_at

Revision ID: c14432b7a7ee
Revises: 8ee1c1e9af23
Create Date: 2026-09-07 17:38:50.774794

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import sqlite

revision = 'c14432b7a7ee'
down_revision = '8ee1c1e9af23'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('random_draws',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('expo_id', sa.Integer(), nullable=False),
    sa.Column('prize', sa.String(length=300), nullable=False),
    sa.Column('winners_count', sa.Integer(), nullable=False),
    sa.Column('candidates_hash', sa.String(length=20), nullable=False),
    sa.Column('winner_user_ids', sqlite.JSON(), nullable=False),
    sa.Column('created_by', sa.BigInteger(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['expo_id'], ['expos.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_random_draws_expo_id'), 'random_draws', ['expo_id'], unique=False)
    op.add_column('broadcasts', sa.Column('scheduled_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('broadcasts', 'scheduled_at')
    op.drop_index(op.f('ix_random_draws_expo_id'), table_name='random_draws')
    op.drop_table('random_draws')
    # ### end Alembic commands ###
